:log_path: /a_path/via.log
:mongo:
  :address: localhost
  :port: 27017
  :db_name: via
:blog_details:
  :title: dpitt.me
  :title_html: 'dpitt:~<span style="font-size: 36px;">$</span>'
  :subtitle: On which I blog about nothing
  :author: dan pittman
